import type { Caravan, WorldState, GoodId, Road } from './types'
import { ROAD_SPEED } from '../lib/constants'
import { seasonSpeedMultiplier } from './seasons'
import { distance } from '../lib/math'
import { caravanId, eventId } from '../lib/ids'
import type { GameEvent } from './types'

/**
 * Find the direct road between two settlements if it exists, else null.
 * For now we use direct road lookup; later can add Dijkstra for multi-hop.
 */
export function findRoad(fromId: string, toId: string, roads: Road[]): Road | null {
  return roads.find(
    r => (r.fromId === fromId && r.toId === toId) || (r.fromId === toId && r.toId === fromId)
  ) ?? null
}

/**
 * Get effective speed per fast tick for a caravan on a given road, adjusted for season.
 */
export function getCaravanSpeed(road: Road, world: WorldState): number {
  const baseSpeed = ROAD_SPEED[road.quality] ?? ROAD_SPEED.gravel
  const seasonMult = seasonSpeedMultiplier(world.season)
  return baseSpeed * seasonMult
}

/**
 * Move all caravans forward one fast tick.
 * Returns an array of caravans that have arrived this tick (progress >= 1).
 */
export function moveCaravans(world: WorldState): Caravan[] {
  const arrived: Caravan[] = []

  for (const caravan of Object.values(world.caravans)) {
    const road = findRoad(caravan.fromId, caravan.toId, world.roads)
    if (!road) {
      // No road found — use a slow default (shouldn't normally happen)
      caravan.progress += 0.005
    } else {
      caravan.progress += getCaravanSpeed(road, world)
    }

    if (caravan.progress >= 1.0) {
      caravan.progress = 1.0
      arrived.push(caravan)
    }
  }

  return arrived
}

/**
 * Process a caravan arrival: deliver cargo, pay merchant, remove caravan.
 * Returns events generated by the delivery.
 */
export function deliverCaravan(caravan: Caravan, world: WorldState): GameEvent[] {
  const events: GameEvent[] = []
  const destination = world.settlements[caravan.toId]
  const merchant = world.merchants[caravan.merchantId]

  if (!destination || !merchant) {
    // Orphaned caravan — just remove it
    delete world.caravans[caravan.id]
    return events
  }

  let revenue = 0
  const deliveredGoods: string[] = []

  for (const [goodId, quantity] of Object.entries(caravan.cargo) as [GoodId, number][]) {
    if (quantity <= 0) continue

    // Add goods to destination inventory
    destination.inventory[goodId] = (destination.inventory[goodId] ?? 0) + quantity

    // Calculate revenue at destination price
    const sellPrice = destination.prices[goodId] ?? 0
    const tariff = destination.tariffRate
    const grossRevenue = sellPrice * quantity
    const tariffPaid = grossRevenue * tariff
    revenue += grossRevenue - tariffPaid

    // Add tariff to destination treasury (lord's income)
    destination.treasury += tariffPaid

    deliveredGoods.push(`${quantity.toFixed(1)} ${goodId}`)
  }

  // Pay merchant
  merchant.gold += revenue
  merchant.caravanId = undefined
  merchant.idleTicks = 0

  // Short summary event
  const goodsSummary = deliveredGoods.slice(0, 2).join(', ')
    + (deliveredGoods.length > 2 ? ` +${deliveredGoods.length - 2} more` : '')

  events.push({
    id: eventId(),
    tick: world.fastTick,
    dayTick: world.slowTick,
    type: 'caravan_arrived',
    message: `${merchant.name}'s caravan delivered ${goodsSummary} to ${destination.name}. Revenue: ${revenue.toFixed(0)}g.`,
    settlementId: caravan.toId,
  })

  // Remove the caravan from world state
  delete world.caravans[caravan.id]

  return events
}

/**
 * Dispatch a new caravan for a merchant.
 * Deducts cargo cost from source settlement inventory.
 * Returns the new Caravan, or null if it can't be created (no road, no stock).
 */
export function dispatchCaravan(
  merchantId: string,
  fromId: string,
  toId: string,
  cargo: Partial<Record<GoodId, number>>,
  world: WorldState,
): Caravan | null {
  const road = findRoad(fromId, toId, world.roads)
  if (!road) return null

  const source = world.settlements[fromId]
  if (!source) return null

  // Deduct cargo from source inventory
  for (const [goodId, quantity] of Object.entries(cargo) as [GoodId, number][]) {
    const available = source.inventory[goodId] ?? 0
    if (available < quantity) return null
    source.inventory[goodId] = available - quantity
  }

  const speed = getCaravanSpeed(road, world)
  const caravan: Caravan = {
    id: caravanId(),
    merchantId,
    fromId,
    toId,
    cargo,
    progress: 0,
    speed,
    returning: false,
    purchaseCost: 0, // simplified — could track cost for profit calc
  }

  world.caravans[caravan.id] = caravan

  const merchant = world.merchants[merchantId]
  if (merchant) {
    merchant.caravanId = caravan.id
  }

  return caravan
}

/**
 * Compute the approximate travel time (in slow ticks / days) for a route.
 */
export function estimateTravelDays(fromId: string, toId: string, roads: Road[]): number {
  const road = findRoad(fromId, toId, roads)
  if (!road) return 999

  const baseSpeed = ROAD_SPEED[road.quality] ?? ROAD_SPEED.gravel
  // Progress per fast tick → ticks to complete = 1/speed
  // 10 fast ticks per slow tick (day)
  const fastTicksNeeded = 1 / baseSpeed
  return fastTicksNeeded / 10
}
